spring:
  application:
    name: custom-payment-system
  input:
    directory: /Users/levandr/IdeaProjects/custom-payment-system/src/main/resources/Input
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: levandr
    password: levandr
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  profiles:
    active: test
